### PR TITLE
Make MovementController compatible with 2018.2, fixes some errors with ExampleCharacter, CameraControl and IKHandler

### PR DESCRIPTION
**Pull request by PcJax**
The ground detection was not working on 2018.2 due to some changes to ControllerColliderHit.normal that breaks de MovementController logic, now it has a workaround that works on that and previous versions.

ExampleCharacter had some PredVar that were never initialized and gives some errors or warnings.

CameraControl had errors when CROSS_PLATFORM_INPUT was disabled.

IKHandler was giving some random error on "Quaternion.Lerp (rightRotLast, rightRotTarget, heightLerpCurve.Evaluate((Time.time - rightTime) / rightStepTime));", when the result of heightLerpCurve.Evaluate was zero the Quaternion.Lerp broke into an error, it was really low incidence issue, a workaround was made to avoid that error.

CrossPlatformInput was upgraded to reduce some compilation warnings.

New Terrain.asset was moved inside the UnetController/Terrains folder, because if the user only import the UnetController folder in their project the Demo Scene was broken.

### CODE REVIEW

**Comment by h33p** [comment]
Great work! Honestly, I did not see this coming.

This clearly underlines all the mistakes I happened to make and fixes them. There also seems to be some work in progress when it comes to mirror support, but once it is finished, I will be able merge it as soon as I get unity up and running again on my system. Also, there is this mixture of tabs and spaces that I do not really like (regarding code consistency), that I will also have to fix, but other than that, I really do welcome the changes.

**Comment by PcJax** [comment]
Sorry about the mixes of tabs and spaces, visual studio make those and I forget to avoid them on some files, also the Mirror support was supposed to be another branch to allow the pull request with only the bug fixes, that was a serious mistake of my part.

I was using your controller for a couple months and I really like it, but I have not used github before and now I have lot of work pending to share so sorry if it seems like a bit rushed.

**Comment by h33p** [comment]
No problem. I will probably merge in just the bug fixes if the rest is not ready, but I have got no promises of when exactly, since I have not touched Unity in months now.

**Comment by Heep042** [comment]
Okay, I have made up my mind. I will merge in the bug fixes only, without bringing in any new features (that is going to happen in a few days). The current state of the project is almost as good as it could get without doing any API breaking changes. I would rather focus on building a new system (or collection of tools) around ECS rather than extending this project. But that is just me, I welcome any forks implementing more features in this OOP style system.

**Review by h33p — APPROVED** [review]

**Review by h33p — APPROVED** [review]

**Review by h33p — CHANGES_REQUESTED** [review]
Spaces are used for indentation, while the project uses tabs.

**Review by h33p — CHANGES_REQUESTED** [review]
Inconsistent indentation.

**Review by h33p — APPROVED** [review]

**Review by h33p — CHANGES_REQUESTED** [review]
Inconsistent indentation, check against Vector3.zero - possible GC allocation, unnecessary branch (a faster solution has already been pushed).

**Review by h33p — APPROVED** [review]

**Review by h33p — APPROVED** [review]

**Review by h33p — APPROVED** [review]

**Review by h33p — APPROVED** [review]

**Review by h33p — COMMENTED** [review]
Mirror will not be merged into this repo, so I guess I will fix this manually later on.

**Pull request closed without merging**
